# Setting can be seen here
# https://docs.astral.sh/ruff/settings/

# Line lenght override
line-length = 120
indent-width = 4

# In addition to the standard set of exclusions, omit all tests, plus a specific file.
extend-exclude = ["_version.py", "versioneer.py"]

# Assume at least Python 3.10, code will be compatible with 3.10 or later
target-version = "py310"

[format]
# Keep the quotes as they are
quote-style = "preserve"
skip-magic-trailing-comma = false

[lint.isort]
combine-as-imports = true
